# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8772cfd2815d09f721394db34f997d86"
name = "pritablebutton-app"
handle = "pritablebutton-app-1"
application_url = "https://concrete-lowest-biographies-loaded.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_customers,write_customers"

[auth]
redirect_urls = ["https://concrete-lowest-biographies-loaded.trycloudflare.com/auth/callback", "https://concrete-lowest-biographies-loaded.trycloudflare.com/auth/shopify/callback", "https://concrete-lowest-biographies-loaded.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

# App Proxy config so CLI deploy preserves your proxy instead of removing it
[app_proxy]
prefix = "apps"
# The path shoppers visit on the store, e.g. https://{shop}/apps/data/...
subpath = "proxy"
# Where Shopify forwards requests. It will append the remainder of the path and query.
# This should point to your backend route that handles the proxy, which is /data/* in this app.
url = "https://concrete-lowest-biographies-loaded.trycloudflare.com/data/info"
